- name: Install a base admin level system
  hosts: all

  tasks:
 
  - name: Ensure Google Chrome is installed via Chocolatey
    win_chocolatey:
      name: googlechrome
      state: present

  - name: Ensure VLC Player is installed via Chocolatey
    win_chocolatey:
      name: vlc
      state: present

  - name: Ensure Office365 is installed via Chocolatey
    win_chocolatey:
      name: office365proplus
      state: present

